### ISSUE TITLE
Polish UI on existing wireframes

### ISSUE THREAD

**Issue by Leikela** [CodeDoesGood/MercuryBack#42]
I am working on the visual design/UI for these existing wireframes:

- Login --ready for dev
- Home (after login) --ready for dev
- Project List -- ready for dev
- Project Detail -- _may need some discussion prior to dev_
- User Profile
- Contact - add subject/project?
- Activity Detail (project)
- Activity Timeline (project) 

As each page is ready I will upload to Zeplin.  https://zpl.io/amEvBDa

**Comment by Leikela** [comment]
Please take a look at the Activity Detail page in Zeplin https://zpl.io/adx7nrn  I have made some comments and would like the group's input.

**Comment by tehstun** [comment]
Closed due to migration of UI work
