### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by Leikela** [CodeDoesGood/MercuryBack#43]
I am working on standardizing the colors and fonts across all pages so that we can have a concise and easy to follow style guide.  This should extend to iOS and Android Apps.

**Comment by northtwilight** [comment]
Thumbs up! Please drop a heads' up to Michael and the project leads as I'd
like them to add OS-specific hooks [ie app extensions ] to handle
conformance automatically in conjunction with your style guidelines

**Comment by tehstun** [comment]
Moved to mercury front.
