### ISSUE TITLE
Create Wireframes

### ISSUE THREAD

**Issue by Leikela** [CodeDoesGood/MercuryBack#44]
I have identified the following wireframes that need to be designed.  Feel free to make suggestions. 

- User profile: comment input
- Sign-up page
- Forgot password dialog/interaction
- Exportable comment page (PDF)
- Company announcement submission screen
- Dismiss announcement confirmation/alert
- Admin dashboard--see Issue #20 
- Admin area - report who has not confirmed they have read an announcement
- Project page: edit mode

I will update this issue as I complete them.

**Comment by tehstun** [comment]
Moved to mercury front.
