### ISSUE TITLE
User Testing

### ISSUE THREAD

**Issue by Leikela** [CodeDoesGood/MercuryBack#45]
Is there a group of users that we can tap for testing a prototype for feedback?  I don't have one ready yet, but if we have testers, I could create a prototype to test the user flow and interactions prior to development. Thoughts?

**Comment by northtwilight** [comment]
In this case it's just us as users and admins as the project is really
intended for our internal use. Great idea however; if the web system gets
used by other nonprofit groups a workable prototype will 'sell' or market
it very well indeed. It will also help when it comes time to pull
documentation together...

**Comment by tehstun** [comment]
Closed due to 60+ days of inactivity.
